server:
  port: 8992

spring:
  dubbo:
    #服务类包目录
    base-package: io.github.wangmeng.consumer.rest
    protocol:
      #协议端口
      port: 20880
      #协议名称
      name: dubbo
    registry:
      #注册中心地址
      address: zookeeper://127.0.0.1:2181
    application:
      #应用名称
      name: consumer
